[project]
name = "dbui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.63",
    "dotenv>=0.9.9",
    "textual>=6.4.0",
]
